source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
inhibit_all_warnings!

target 'AMBase' do

pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'MJExtension'
pod 'Masonry', :inhibit_warnings => true
pod 'MyLayout', :inhibit_warnings => true
pod 'Aspects'

end


